"use strict";
// Copyright (c) jdneo. All rights reserved.
// Licensed under the MIT license.
Object.defineProperty(exports, "__esModule", { value: true });
exports.langExt = exports.languages = void 0;
exports.languages = [
    "bash",
    "c",
    "cpp",
    "csharp",
    "golang",
    "java",
    "javascript",
    "kotlin",
    "mysql",
    "php",
    "python",
    "python3",
    "ruby",
    "rust",
    "scala",
    "swift",
    "julia",
    "souffle",
    "ocaml",
    "sql",
    "prolog",
    "elpi",
    "minizinc",
    "whyml",
    "x86",
    "clingo",
    "cvc5",
    "z3",
    "scheme",
    "racket",
    "ciao",
    "scryer"
];
exports.langExt = new Map([
    ["bash", ".sh"],
    ["c", ".c"],
    ["cpp", ".cpp"],
    ["csharp", ".cs"],
    ["golang", ".go"],
    ["java", ".java"],
    ["javascript", ".js"],
    ["kotlin", ".kt"],
    ["mysql", ".sql"],
    ["php", ".php"],
    ["python", ".py"],
    ["python3", ".py"],
    ["ruby", ".rb"],
    ["rust", ".rs"],
    ["scala", ".scala"],
    ["swift", ".swift"],
    ["julia", ".jl"],
    ["ocaml", ".ml"],
    ["souffle", ".dl"],
    ["sql", ".sql"],
    ["prolog", ".pl"],
    ["elpi", ".elpi"],
    ["minizinc", ".mzn"],
    ["whyml", ".why3"],
    ["x86", ".s"],
    ["clingo", ".lp"],
    ["cvc5", ".smt2"],
    ["z3", ".smt2"],
    ["scheme", ".scm"],
    ["racket", ".rkt"],
    ["ciao", ".pl"],
    ["scryer", ".pl"]
]);
//# sourceMappingURL=share.js.map
